python game_split_CoNN.py 2 0 &
python game_split_CoNN.py 2 1 &
python game_split_CoNN.py 2 2 &
python game_split_CoNN.py 2 3 &
python game_split_CoNN.py 2 4 &
python game_split_CoNN.py 2 5 &
python game_split_CoNN.py 2 6 &
python game_split_CoNN.py 2 7 &
python game_split_CoNN.py 2 8 &
python game_split_CoNN.py 2 9 &
